default:
  image: docker/compose:alpine-1.29.2
  tags:
    - docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GOOGLE_TAG_LATEST: eu.gcr.io/papers-dev-kubernetes/$CI_PROJECT_NAMESPACE/ci_$CI_PROJECT_NAME:latest

services:
  - docker:dind

stages:
  - setup
  - checks
  - compile
  - test

# .before_docker_build:
#   image: google/cloud-sdk
#   before_script:
#     - echo $GCLOUD_GOOGLE_KEY_DEV > key.json
#     - gcloud auth activate-service-account $GCLOUD_ACCOUNT_DEV --key-file key.json
#     - gcloud config set account $GCLOUD_ACCOUNT_DEV
#     - gcloud config set project $GCLOUD_PROJECT_DEV
#     - gcloud config set compute/zone $GCLOUD_ZONE_DEV
#     - gcloud container clusters get-credentials papers-cluster-development
#     - gcloud auth configure-docker
#   tags:
#     - docker

# docker_build:
#   extends: .before_docker_build
#   stage: setup
#   script:
#     - docker build -t $GOOGLE_TAG_LATEST .
#     - docker push $GOOGLE_TAG_LATEST

# .setup:
#   image: $GOOGLE_TAG_LATEST
#   before_script:
#     - cp -r /_build .
#     - make
#   when: always
#   tags:
#     - docker

.setup:
  image: node:latest
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends python3-dev python3-pip python3-setuptools build-essential libsodium-dev libsecp256k1-dev libgmp3-dev git curl
    - make
  when: always
  tags:
    - docker

# format-check:
#   extends: .setup
#   stage: checks
#   script:
#     - make fmt-check

compile_tezos_contracts:
  extends: .setup
  stage: compile
  script:
    - make compile-tezos

compile_evm_contracts:
  extends: .setup
  stage: compile
  script:
    - make compile-evm

test_tezos_contracts:
  extends: .setup
  stage: test
  script:
    - make test-tezos

test_evm_contracts:
  extends: .setup
  stage: test
  script:
    - make test-evm
