image: registry.gitlab.papers.tech/papers/customer-tezos-foundation/inter-blockchain-communication-framework/tezos-sc

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - build
    - node_modules
  policy: pull-push

stages:
  - setup
  - checks
  - compile
  - test

setup:
  cache:
    <<: *global_cache
    policy: pull
  stage: setup
  script:
    - make
  tags:
    - docker

format-check:
  cache:
    <<: *global_cache
    policy: pull
  stage: checks
  before_script:
    - make
  script:
    - make fmt-check
  tags:
    - docker

compile_tezos_contracts:
  cache:
    <<: *global_cache
    policy: pull
  stage: compile
  before_script:
    - make
  script:
    - make compile-tezos
  tags:
    - docker

compile_evm_contracts:
  cache:
    <<: *global_cache
    policy: pull
  stage: compile
  before_script:
    - make
  script:
    - make compile-evm
  tags:
    - docker

test_tezos_contracts:
  cache:
    <<: *global_cache
    policy: pull
  stage: test
  before_script:
    - make
  script:
    - make test-tezos
  tags:
    - docker

test_evm_contracts:
  cache:
    <<: *global_cache
    policy: pull
  stage: test
  before_script:
    - make
  script:
    - make test-evm
  tags:
    - docker
