pytezos:
    rpc_endpoint: https://tezos-ithacanet-node-1.diamond.papers.tech
    private_key: edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq
known_addresses:
    signer_1: tz3LXMyngf729xwrmwV9yUv7jRwmuNvYX3JR
    signer_2: tz1aBNXcSKfWE7aujp2Twa7V7Beua2fjhri3
    signer_3: tz1XvqmBUa7SkUFRHSygUZsxMwh7i8GpV7iB
    eth_client_address: "0xE83051942Da40421021B9CBBfB007038A1F32614"
actions:
    - kind: origination
      contract_kind: IBCF_Aggragator
      name: IBCF_Aggragator
      code_path: __SNAPSHOTS__/compilation/tezos/IBCF_Aggregator/IBCF_Aggregator/step_000_cont_0_contract.tz
      storage: __SNAPSHOTS__/compilation/tezos/IBCF_Aggregator/IBCF_Aggregator/step_000_cont_0_storage.tz
      overrides:
          config:
              administrator: admin_address
              signers:
                  - signer_1
                  - signer_2
                  - signer_3
                  - admin_address
              history_ttl: 4
              max_state_size: 32
              max_states: 5

    - kind: origination
      contract_kind: IBCF_Eth_Validator
      name: IBCF_Eth_Validator
      code_path: __SNAPSHOTS__/compilation/tezos/IBCF_Eth_Validator/IBCF_Eth_Validator/step_000_cont_0_contract.tz
      overrides:
          config:
              administrator: admin_address
              validators:
                  - signer_1
                  - signer_2
                  - signer_3
                  - admin_address
              minimum_endorsements: 1

    - kind: origination
      contract_kind: IBCF_Client
      name: IBCF_Client
      code_path: __SNAPSHOTS__/compilation/tezos/IBCF_Client/IBCF_Client/step_000_cont_0_contract.tz
      storage:
            eth_contract: eth_client_address
            storage_slot: "0x0000000000000000000000000000000000000000000000000000000000000000"
            ibcf_tezos_state: IBCF_Aggragator
            ibcf_eth_validator: IBCF_Eth_Validator
            counter: 0

    # Blueprints

    - kind: origination
      contract_kind: Asset
      name: Asset
      code_path: __SNAPSHOTS__/compilation/tezos/blueprints/BridgedAsset/BridgedAsset/step_000_cont_0_contract.tz
      overrides:
            metadata: {}
            administrator: admin_address

    - kind: origination
      contract_kind: IBCF_Bridge
      name: IBCF_Bridge
      code_path: __SNAPSHOTS__/compilation/tezos/blueprints/IBCF_Bridge/IBCF_Bridge/step_000_cont_0_contract.tz
      overrides:
            registry: {}
            ethereum_nonce: {}
            merkle_aggregator: IBCF_Aggragator
            proof_validator: IBCF_Eth_Validator
            asset_address: Asset
            eth_bridge_address: "0x0C2dBba45E207619B79Fd7946496fbEc1E66fA8C"

    # - kind: contract_call
    #   contract_address: IBCF_Client
    #   entrypoint: update_storage
    #   argument:
    #         eth_contract: eth_client_address
    #         storage_slot: "0x0000000000000000000000000000000000000000000000000000000000000000"
    #         ibcf_tezos_state: IBCF_Aggragator
    #         ibcf_eth_validator: IBCF_Eth_Validator
    #         counter: 0

    # - kind: contract_call
    #   contract_address: IBCF_Client
    #   entrypoint: ping

    # - kind: contract_call
    #   contract_address: IBCF_Aggragator
    #   entrypoint: insert
    #   script: insert_multiple_states
