pytezos:
  rpc_endpoint: https://tezos-ghostnet-node-1.diamond.papers.tech
  private_key: edskS8xUePnvXXp3XHjYkDBBKDRwigGF95uHtJzDakV74azm9y6KHvkw4gLjPUvenWiY7H9xRQN729ipPutLVLiHXHMYfaf9hS
known_addresses:
  signer_1: tz3LXMyngf729xwrmwV9yUv7jRwmuNvYX3JR
  signer_2: tz1aBNXcSKfWE7aujp2Twa7V7Beua2fjhri3
  signer_3: tz1XvqmBUa7SkUFRHSygUZsxMwh7i8GpV7iB
  IBCF_Aggragator: "KT1B8F7BhA2EeGQvPFpaVStd99ZDSzwrAcBL"
actions:
  - kind: origination
    contract_kind: AcurastProxy
    name: AcurastProxy
    code_path: __SNAPSHOTS__/compilation/tezos/AcurastProxy/AcurastProxy/step_000_cont_0_contract.tz
    storage: __SNAPSHOTS__/compilation/tezos/AcurastProxy/AcurastProxy/step_000_cont_0_storage.tz
    overrides:
      config:
        governance_address: admin_address
        merkle_aggregator: IBCF_Aggragator
