pytezos:
  rpc_endpoint: https://tezos-ithacanet-node-1.diamond.papers.tech #http://localhost:20000
  private_key: edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq
known_addresses:
    admin_address: tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
actions:
    - kind: origination
      contract_kind: merkle_tree
      name: merkle_tree
      code_path: __SNAPSHOTS__/compilation/tezos/IBCF/state_aggregator/step_000_cont_0_contract.tz
      storage: __SNAPSHOTS__/compilation/tezos/IBCF/state_aggregator/step_000_cont_0_storage.tz
      overrides:
          config:
              administrators:
                  - admin_address
              history_ttl: 4
              max_state_size: 32
              max_states: 5

    - kind: contract_call
      contract_address: merkle_tree
      entrypoint: insert
      script: insert_multiple_states

    - kind: contract_call
      contract_address: merkle_tree
      entrypoint: snapshot_merkle_tree
      argument:
